"""
LLM Output Schemas - Pydantic models for structured LLM output.

These schemas are used for:
1. Constrained decoding (Outlines) - Forces LLM to output valid JSON
2. Post-validation - Validates parsed JSON from any provider
3. Type hints - Clean interfaces between LLM layer and app layer

NOTE: These are INTERNAL to the LLM layer.
For API response schemas, see app/data/schemas.py
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Literal


# =============================================================================
# Message Processing Schemas
# =============================================================================

class ExtractedTask(BaseModel):
    """Task extracted from email content by LLM."""
    title: str
    description: Optional[str] = None
    priority: Literal["low", "normal", "high", "urgent"] = "normal"
    due_date: Optional[str] = None  # ISO format or natural language
    assignee: Optional[str] = None
    source_snippet: Optional[str] = None
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)


class SchedulingIntent(BaseModel):
    """Scheduling intent detection result."""
    detected: bool = False
    type: Literal[
        "availability_request",
        "time_request", 
        "reschedule_request",
        "meeting_proposal",
        "none"
    ] = "none"
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class ProcessMessageResult(BaseModel):
    """Full message processing output from LLM."""
    summary: str
    needs_reply: bool = False
    tasks: List[ExtractedTask] = []
    dates: List[str] = []
    people: List[str] = []
    decisions: List[str] = []
    scheduling_intent: SchedulingIntent = Field(default_factory=SchedulingIntent)


# =============================================================================
# Thread State Schemas
# =============================================================================

class ThreadStateInit(BaseModel):
    """Initial thread state from first message in a thread."""
    summary: str
    tasks: List[ExtractedTask] = []
    decisions: List[str] = []
    last_action: str
    last_action_by: str = ""
    needs_reply: bool = False
    needs_reply_reason: Optional[str] = None
    scheduling_intent: bool = False
    scheduling_intent_type: str = "none"
    scheduling_intent_confidence: float = 0.0


class TaskStatusUpdate(BaseModel):
    """Update to an existing task's status."""
    title: str  # Match by title since we don't have IDs in LLM context
    new_status: Literal["completed", "dismissed", "open", "blocked"]
    reason: Optional[str] = None


class ThreadStateUpdate(BaseModel):
    """Delta update to thread state from a new message."""
    summary_update: Optional[str] = None
    task_updates: List[TaskStatusUpdate] = []
    new_tasks: List[ExtractedTask] = []
    new_decisions: List[str] = []
    last_action: str
    last_action_by: str = ""
    needs_reply: bool = False
    needs_reply_reason: Optional[str] = None
    scheduling_intent: bool = False
    scheduling_intent_type: str = "none"
    scheduling_intent_confidence: float = 0.0


# =============================================================================
# Reply Generation Schemas
# =============================================================================

class DraftReply(BaseModel):
    """Draft reply generated by LLM."""
    draft: str
    tone: Literal["formal", "casual", "neutral"] = "neutral"
    includes_placeholders: bool = False
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)


class SummaryResult(BaseModel):
    """Simple summary output."""
    summary: str


class NeedsReplyResult(BaseModel):
    """Needs reply classification output."""
    needs_reply: bool
    reason: Optional[str] = None
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)


# =============================================================================
# Extraction Schemas (for individual extraction calls)
# =============================================================================

class TaskExtractionResult(BaseModel):
    """Result of task extraction."""
    tasks: List[ExtractedTask] = []


class DateExtractionResult(BaseModel):
    """Result of date extraction."""
    dates: List[str] = []


class PeopleExtractionResult(BaseModel):
    """Result of people extraction."""
    people: List[str] = []


class DecisionExtractionResult(BaseModel):
    """Result of decision extraction."""
    decisions: List[str] = []

